apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-user
  title: Create a Backstage User
  description: Scaffold a new User entity in Backstage
spec:
  owner: group:default/backstage-admins
  type: administration

  parameters:
    - title: User Information
      required: [username, email, displayName, memberOfString]
      properties:
        username:
          type: string
          title: Username
        email:
          type: string
          title: Email
          format: email
        displayName:
          type: string
          title: Display Name
        memberOfString:
          type: array
          title: Member Of (Groups)
          items:
            type: string
          description: List of groups the user is a member of

  steps:
    - id: template
      name: Generating User YAML
      action: fetch:template
      input:
        url: https://raw.githubusercontent.com/JonFjz/backstage-testing/refs/heads/main/user-skeleton.yaml
        values:
          username: ${{ parameters.username }}
          email: ${{ parameters.email }}
          displayName: ${{ parameters.displayName }}
          memberOfString: ${{ parameters.memberOfString }}

    - id: register
      name: Register User in Backstage Catalog
      action: catalog:register
      input:
        repoContentsUrl: ./user-${{ parameters.username }}.yaml

  output:
  links:
    - title: Open the user YAML
      url: ./user-${{ parameters.username }}.yaml
